use simplex_sdk::arguments::ArgumentsTrait;
use simplex_sdk::program::Program;

use simplicityhl::simplicity::bitcoin::XOnlyPublicKey;

// use simplex_macros::simplex_build;

// #[derive(SimplexBuild)]
// #[simplex("../../contracts/src/asset_auth/source_simf/asset_auth.simf")]
pub struct AssetAuth<'a> {
    program: Program<'a>,
}

impl<'a> AssetAuth<'a> {
    // the path is autogenerated
    pub const SOURCE: &'static str = "";
    // include_str!("../../contracts/src/asset_auth/source_simf/asset_auth.simf");

    pub fn new(public_key: &'a XOnlyPublicKey, arguments: &'a impl ArgumentsTrait) -> Self {
        Self {
            program: Program::new(Self::SOURCE, public_key, arguments),
        }
    }

    pub fn get_program(&self) -> &Program<'a> {
        &self.program
    }
}

// Expanded by macro

pub mod asset_auth_build {
    use simplex_sdk::arguments::ArgumentsTrait;
    use simplex_sdk::witness::WitnessTrait;
    use simplicityhl::value::UIntValue;
    use simplicityhl::value::ValueConstructible;
    use simplicityhl::{Value, WitnessValues};
    use std::collections::HashMap;

    pub struct AssetAuthWitness {
        pub path: (bool, u64, u64),
    }

    pub struct AssetAuthArguments {
        pub first: u64,
        pub second: bool,
    }

    impl WitnessTrait for AssetAuthWitness {
        fn build_witness(&self) -> WitnessValues {
            WitnessValues::from(HashMap::from([(
                simplicityhl::str::WitnessName::from_str_unchecked("PATH"),
                Value::tuple([
                    Value::from(self.path.0),
                    Value::from(UIntValue::U64(self.path.1)),
                    Value::from(UIntValue::U64(self.path.1)),
                ]),
            )]))
        }

        // fn from_witness(_witness: &::simplicityhl::WitnessValues) -> Self {
        //     Self {
        //         path: (false, 0, 0),
        //     }
        // }
    }

    impl ArgumentsTrait for AssetAuthArguments {
        fn build_arguments(&self) -> simplicityhl::Arguments {
            simplicityhl::Arguments::from(HashMap::from([
                (
                    simplicityhl::str::WitnessName::from_str_unchecked("FIRST"),
                    Value::from(UIntValue::U64(self.first)),
                ),
                (
                    simplicityhl::str::WitnessName::from_str_unchecked("SECOND"),
                    Value::from(self.second),
                ),
            ]))
        }

        // fn from_arguments(_args: &simplicityhl::Arguments) -> Self {
        //     Self {
        //         first: 0,
        //         second: false,
        //     }
        // }
    }
}
