#!/usr/bin/env bash
set -eo pipefail

echo "Installing simplexup..."

BASE_DIR="${XDG_CONFIG_HOME:-$HOME}"
SIMPLEX_DIR="${SIMPLEX_DIR:-"$BASE_DIR/.simplex"}"
SIMPLEX_BIN_DIR="$SIMPLEX_DIR/bin"

BIN_URL="https://raw.githubusercontent.com/BlockstreamResearch/simplex/HEAD/simplexup/simplexup"
BIN_PATH="$SIMPLEX_BIN_DIR/simplexup"

# Create the .simplex bin directory and simplexup binary if it doesn't exist.
mkdir -p "$SIMPLEX_BIN_DIR"
curl -sSf -L "$BIN_URL" -o "$BIN_PATH"
chmod +x "$BIN_PATH"

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE="${ZDOTDIR-"$HOME"}/.zshenv"
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*)
    echo "simplexup: could not detect shell, manually add ${SIMPLEX_BIN_DIR} to your PATH."
    exit 1
esac

# Only add simplexup if it isn't already in PATH.
if [[ ":$PATH:" != *":${SIMPLEX_BIN_DIR}:"* ]]; then
    # Add the simplexup directory to the path and ensure the old PATH variables remain.
    echo >> "$PROFILE" && echo "export PATH=\"\$PATH:$SIMPLEX_BIN_DIR\"" >> "$PROFILE"
fi

## Warn MacOS users that they may need to manually install libusb via Homebrew:
#if [[ "$OSTYPE" =~ ^darwin ]] && [[ ! -f /usr/local/opt/libusb/lib/libusb-1.0.0.dylib ]] && [[ ! -f /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib ]]; then
#    echo && echo "warning: libusb not found. You may need to install it manually on MacOS via Homebrew (brew install libusb)."
#fi

echo
echo "Detected your preferred shell is $PREF_SHELL and added simplexup to PATH."
echo "Run 'source $PROFILE' or start a new terminal session to use simplexup."
echo "Then, simply run 'simplexup' to install Simplex."
