# TEST CONFIG 

# [build]
# simf_files = ["*.simf"]
# out_dir = "./src/artifacts"
# src_dir = "./simf"

[test]
esplora = "https://blockstream.info/liquidtestnet/api"

# [test.rpc]
# url = "rpc_url"
# username = "username"
# password = "password"
