# TEST CONFIG 

# [build]
# simf_files = ["*.simf"]
# out_dir = "./src/artifacts"
# src_dir = "./simf"

# [test]
# esplora = "esplora_api_url"

# [test.rpc]
# url = "rpc_url"
# username = "username"
# password = "password"
